image: node:16.15.1
stages:
  - install_deps
  - build_prod
  - deploy_prod

# 拉取项目
# variables:
#   GIT_SUBMODULE_STRATEGY: recursive
variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR

cache:
  paths:
    - node_modules/
    - dist

# 安装构建依赖
install_deps_job:
  stage: install_deps
  only:
    - master
  script:
    - echo '安装构建依赖阶段'
    - pwd
    - npm install # 安装依赖
  tags:
    - build,deploy
# 打包新文件
build_prod_job:
  stage: build_prod
  # variables:
  #   GIT_STRATEGY: none
  only:
    - master
  script:
    - echo '打包新文件阶段'
    - ls
    - pwd
    - rm -rf ./dist # 删除当前文件夹下的 dist 文件夹
    - npm run build # 打包
    - ls
  tags:
    - build,deploy
# 登录项目部署服务器，移除旧版本项目文件，最后将打包好的文件拷贝过去
deploy_prod_job:
  stage: deploy_prod
  # variables:
  #   GIT_STRATEGY: none
  only:
    - master
  script:
    - echo '登录项目部署服务器，移除旧版本项目文件，最后将打包好的文件拷贝过去'
    - rm -rf /home/www/wwwroot/cloudspace && mkdir -p /home/www/wwwroot/cloudspace
    # - \cp -rf ./dist /usr/local/nginx/html
    # - cp -rf dist/* /home/www/wwwroot/cloudspace
    - pwd   
    # /home/www/wwwroot/testbuid/vite-front
    - ls
    # - cp ./dist/ /home/www/wwwroot/cloudspace/ -r
    - cp dist/* /home/www/wwwroot/cloudspace -rf
  tags:
    - build,deploy
  # 重新触发构建
  
