version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.17
    working_directory: ~/cloudspace
    branches:
      only:
        - master
    machine:  # 以虚拟机的方式运行
      enabled: true
    steps:
      - checkout
      - run: sudo npm install -g npm@6
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build:pro
      - run: echo '部署开始'
      - run: sudo apt-get update && sudo apt-get install rsync
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "5d:d8:5e:09:c4:cc:57:2f:e4:3b:7e:49:2a:b3:f0:24"
       
      # - run: sudo apt-get update && sudo apt-get install rsync && sudo apt-get install openssh-client
      - run: pwd
      # - run: echo $REMOTE_HOSTKEY >> /home/circleci/.ssh/known_hosts
      - run: ls
      # - run:
      #     name: Deploy Over SSH
      #     command: ssh $SSH_USER@$SSH_IP 
          # scp -v /home/knowledge/aaa.ts $SSH_USER@$SSH_IP:/www/wwwroot/testbuild/
      - deploy:
          name: deploy
          command: scp -v /home/knowledge/cloudspace/dist/* $SSH_USER@$SSH_IP:/www/wwwroot/testbuild/
          # command: |
          #   ls
          #   pwd
            
          #   if [ "${CIRCLE_BRANCH}" = "main" ]; then
          #     rsync -avce ssh /home/knowledge/aaa.ts $SSH_USER@$SSH_IP:/www/wwwroot/testbuild/
          #   else
          #     echo "Not master branch, dry run only"
          #   fi
      - run: echo '部署完毕啊'
# workflows:
#   version: 2
#   scheduled-workflow:
#     jobs:
#       - build
      # - run:
      #     name: Prepare shell commands
      #     command: chmod +x deploy.sh
      # - run:
      #     name: Run Deploy to Github pages
      #     command: ./deploy.sh