version: 2
jobs:
  build:
    docker:
      - image: cimg/node:20.9.0
    # 表示circle登录后 直接倒了/home/circleco/cloudspace这个目录下了
    working_directory: ~/cloudspace
    branches:
      only:
        - master
    machine:  # 以虚拟机的方式运行
      enabled: true
    steps:
      - checkout
      - run: sudo npm install -g npm@6
      - run: npm install
      - run: echo '删除原来的dist目录'
      - run: rm -rf /home/circleci/cloudspace/dist
      - run: echo '开始构建'
      - run: npm run build:pro
      - add_ssh_keys:
          fingerprints:
            - "06:f4:f6:4a:9d:43:0d:9e:0a:dd:15:33:27:0a:bf:3f"
      - run: ls
          name: '开始部署'
          command: scp -vr  -o StrictHostKeyChecking=no /home/circleci/cloudspace/dist/* $SSH_USER@$SSH_IP:/www/wwwroot/cloudspace/
      - run: echo '部署完毕啊'